// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CssSorter
{
    static class Vsix
    {
        public const string Id = "87534672-5a41-4ea1-a145-17f1a8f5502a";
        public const string Name = "CSS Sorter";
        public const string Description = @"Sort CSS properties easily for better readibility and GZIP compression";
        public const string Language = "en-US";
        public const string Version = "0.6";
        public const string Author = "Mads Kristensen";
        public const string Tags = "CSS, LESS, Sass, Scss, Sorting";
    }
}
