// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CssSorter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "fe3dc58f-c4c7-4d03-a8de-a53fbcf7ee20";
        public const string guidPackageCmdSetString = "e4cb03b4-95a5-4808-b6c6-d6f24387d39b";
        public const string CssEditorString = "a5401142-f49d-43db-90b1-f57ba349e55c";
        public const string CssEditorWithEncodingString = "226f7e34-0ae8-4157-9cd8-b66b4eaf2c7b";
        public const string CssCmdSetString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
        public static Guid CssEditor = new Guid(CssEditorString);
        public static Guid CssEditorWithEncoding = new Guid(CssEditorWithEncodingString);
        public static Guid CssCmdSet = new Guid(CssCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuGroup = 0x1020;
        public const int SettingsGroup = 0x1030;
        public const int ExecuteGroup = 0x1040;
        public const int ContextMenu = 0x1200;
        public const int SortId = 0x0100;
        public const int SortAlphabeticallyId = 0x0200;
        public const int SortSmacssId = 0x0300;
        public const int SortconcentricId = 0x0400;
        public const int cssContextMenu = 0x0002;
    }
}
